In [12]:
import numpy as np

In [14]:
np.__version__

'1.18.5'

In [9]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9]
type(l)

list

In [15]:
a = np.array(l)
type(a)

numpy.ndarray

In [16]:
b = np.array([2,4,6])
b

array([2, 4, 6])

In [17]:
b.shape

(3,)

In [22]:
d = np.array([[1,2,3, 10],[4,5,6, 10], [7,8,9, 10]])
d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [23]:
d.shape

(3, 4)

In [25]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a[4]

5

In [29]:
d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [31]:
d[1, 2]

6

In [32]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[2:6]

array([3, 4, 5, 6])

In [36]:
d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [43]:
d[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])